export type DemoResult = {
  id: string;
  inputUrl: string;
  outputUrl: string;
  label: string;
  defectId: string;
  confidence: number;
};

export const DEMO_RESULTS: Record<string, DemoResult> = {
  img01: {
    id: "img01",
    inputUrl: "/demo/inputs/img01.jpg",
    outputUrl: "/demo/outputs/img01_out.jpg",
    label: "Open Circuit",
    defectId: "D-OC-01",
    confidence: 0.93,
  },
  img02: {
    id: "img02",
    inputUrl: "/demo/inputs/img02.jpg",
    outputUrl: "/demo/outputs/img02_out.jpg",
    label: "Short Circuit",
    defectId: "D-SC-02",
    confidence: 0.91,
  },
  img03: {
    id: "img03",
    inputUrl: "/demo/inputs/img03.jpg",
    outputUrl: "/demo/outputs/img03_out.jpg",
    label: "Mouse Bite",
    defectId: "D-MB-03",
    confidence: 0.89,
  },
  img04: {
    id: "img04",
    inputUrl: "/demo/inputs/img04.jpg",
    outputUrl: "/demo/outputs/img04_out.jpg",
    label: "Spur",
    defectId: "D-SP-04",
    confidence: 0.87,
  },
  img05: {
    id: "img05",
    inputUrl: "/demo/inputs/img05.jpg",
    outputUrl: "/demo/outputs/img05_out.jpg",
    label: "Copper Residue",
    defectId: "D-CR-05",
    confidence: 0.90,
  },
  img06: {
    id: "img06",
    inputUrl: "/demo/inputs/img06.jpg",
    outputUrl: "/demo/outputs/img06_out.jpg",
    label: "Pin Hole",
    defectId: "D-PH-06",
    confidence: 0.88,
  },
  img07: {
    id: "img07",
    inputUrl: "/demo/inputs/img07.jpg",
    outputUrl: "/demo/outputs/img07_out.jpg",
    label: "Open Circuit",
    defectId: "D-OC-07",
    confidence: 0.94,
  },
  img08: {
    id: "img08",
    inputUrl: "/demo/inputs/img08.jpg",
    outputUrl: "/demo/outputs/img08_out.jpg",
    label: "Short Circuit",
    defectId: "D-SC-08",
    confidence: 0.92,
  },
  img09: {
    id: "img09",
    inputUrl: "/demo/inputs/img09.jpg",
    outputUrl: "/demo/outputs/img09_out.jpg",
    label: "Mouse Bite",
    defectId: "D-MB-09",
    confidence: 0.86,
  },
  img10: {
    id: "img10",
    inputUrl: "/demo/inputs/img10.jpg",
    outputUrl: "/demo/outputs/img10_out.jpg",
    label: "Spur",
    defectId: "D-SP-10",
    confidence: 0.85,
  },
  img11: {
    id: "img11",
    inputUrl: "/demo/inputs/img11.jpg",
    outputUrl: "/demo/outputs/img11_out.jpg",
    label: "Copper Residue",
    defectId: "D-CR-11",
    confidence: 0.91,
  },
  img12: {
    id: "img12",
    inputUrl: "/demo/inputs/img12.jpg",
    outputUrl: "/demo/outputs/img12_out.jpg",
    label: "Pin Hole",
    defectId: "D-PH-12",
    confidence: 0.88,
  },
  img13: {
    id: "img13",
    inputUrl: "/demo/inputs/img13.jpg",
    outputUrl: "/demo/outputs/img13_out.jpg",
    label: "Open Circuit",
    defectId: "D-OC-13",
    confidence: 0.95,
  },
  img14: {
    id: "img14",
    inputUrl: "/demo/inputs/img14.jpg",
    outputUrl: "/demo/outputs/img14_out.jpg",
    label: "Short Circuit",
    defectId: "D-SC-14",
    confidence: 0.93,
  },
  img15: {
    id: "img15",
    inputUrl: "/demo/inputs/img15.jpg",
    outputUrl: "/demo/outputs/img15_out.jpg",
    label: "Mouse Bite",
    defectId: "D-MB-15",
    confidence: 0.87,
  },
  img16: {
    id: "img16",
    inputUrl: "/demo/inputs/img16.jpg",
    outputUrl: "/demo/outputs/img16_out.jpg",
    label: "Spur",
    defectId: "D-SP-16",
    confidence: 0.86,
  },
  img17: {
    id: "img17",
    inputUrl: "/demo/inputs/img17.jpg",
    outputUrl: "/demo/outputs/img17_out.jpg",
    label: "Copper Residue",
    defectId: "D-CR-17",
    confidence: 0.92,
  },
  img18: {
    id: "img18",
    inputUrl: "/demo/inputs/img18.jpg",
    outputUrl: "/demo/outputs/img18_out.jpg",
    label: "Pin Hole",
    defectId: "D-PH-18",
    confidence: 0.89,
  },
  img19: {
    id: "img19",
    inputUrl: "/demo/inputs/img19.jpg",
    outputUrl: "/demo/outputs/img19_out.jpg",
    label: "Open Circuit",
    defectId: "D-OC-19",
    confidence: 0.94,
  },
  img20: {
    id: "img20",
    inputUrl: "/demo/inputs/img20.jpg",
    outputUrl: "/demo/outputs/img20_out.jpg",
    label: "Short Circuit",
    defectId: "D-SC-20",
    confidence: 0.92,
  },
};
